language: objective-c
osx_image: xcode7.3
script:
  xcodebuild test -project PassLockDemo.xcodeproj -scheme PassLock -destination "platform=iOS Simulator,name=iPhone 6,OS=8.1" -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.0"
